version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=postgresql://postgres:waIsiKtBzzncSxrWQbNnntXnTYmmKhpm@turntable.proxy.rlwy.net:45661/railway
      - PORT=8080
    command: go run cmd/server/main.go 